#Spring-Mysql
spring:
  datasource:
    password: Ljh0611.
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.134.252:3306/warehouse?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true

  jpa:
    database: default
    # 开发时显示sql，部署到生产环境时设为false
    show-sql: true
    # 使用mysql方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # 下面两个配置对应hibernate的属性
      ddl-auto: update
    properties:
      hibernate:
        # 格式化sql 语句
        format_sql: true

